### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by PPWangyc** [sbci-brain/SBCI_Pipeline#3]
I am using SBCI to process a batch of data. The pipeline has same error when processing a few subjects. The error may related to the surface calculation using vtk package. I am not sure if this error happened because of previous steps or minimal preprocessing issue.

The error is from sbci_step2_prepare_set.sh
`Traceback (most recent call last):
  File "/home/ywang330/.conda/envs/sbci/bin/scil_surface_from_volume.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/gpfs/fs1/home/ywang330/scilpy_set/scripts/scil_surface_from_volume.py", line 144, in <module>
    main()
  File "/gpfs/fs1/home/ywang330/scilpy_set/scripts/scil_surface_from_volume.py", line 140, in main
    mesh.save(args.out_surface)
  File "/home/ywang330/.conda/envs/sbci/lib/python2.7/site-packages/trimeshpy/trimesh_vtk.py", line 334, in save
    self.update()
  File "/home/ywang330/.conda/envs/sbci/lib/python2.7/site-packages/trimeshpy/trimesh_vtk.py", line 180, in update
    self.update_polydata()
  File "/home/ywang330/.conda/envs/sbci/lib/python2.7/site-packages/trimeshpy/trimesh_vtk.py", line 79, in update_polydata
    self.set_polydata_triangles(self.get_triangles())
  File "/home/ywang330/.conda/envs/sbci/lib/python2.7/site-packages/trimeshpy/trimesh_vtk.py", line 90, in set_polydata_triangles
    np.c_[np.ones(len(triangles)).astype(np.int) * 3, triangles])
  File "/home/ywang330/.conda/envs/sbci/lib/python2.7/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: need at least one array to concatenate`

Here is the sbci_step2_prepare_set.sh scrip:
<img width="1133" alt="image" src="https://github.com/sbci-brain/SBCI_Pipeline/assets/65028679/f4b59fc1-6d4e-44a4-aeb8-26fed0742879">

Please let me know if I need to provide more info. Thank you!

**Comment by MartyCole** [comment]
Sometimes Freesurfer's recon-all command fails to create surfaces. Check the subjects that are failing, do they have surfaces from Freesurfer? If not, I suggest looking at the pial and white vomumes for errors in the t1_freesurfer folder of the problematic subjects. See: https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/TroubleshootingData for more information
